import io
from datetime import datetime

def generate_report(messages):
    """
    Generates a comprehensive Markdown report from the chat history.
    """
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    
    report_content = f"""# 💼 Cofinance Analyst Report

**Generated:** {timestamp}

---

"""
    
    for idx, msg in enumerate(messages, 1):
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        has_chart = bool(msg.get("chart"))
        
        if role == "assistant":
            report_content += f"## 🤖 Analysis #{idx//2 + 1}\n\n"
            report_content += f"{content}\n\n"
            if has_chart:
                report_content += "_📊 Chart included (view in app)_\n\n"
            report_content += "---\n\n"
        elif role == "user":
            report_content += f"### 👤 Query\n\n> {content}\n\n"
    
    report_content += f"""
---

**Report End**

_Generated by Cofinance Analyst - AI-Powered Investment Research Platform_
"""
            
    return report_content
